/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.water.metamodel.account;

import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.water.metamodel.account.Account.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Wed Jul 17 13:16:01 CST 2013")
public class Account_ {
    public static volatile SingularAttribute<Account,AccountAdmin> accountAdmin;
    public static volatile SetAttribute<Account,AccountLog> accountLogs;
    public static volatile SingularAttribute<Account,AccountWeb> accountWeb;
    public static volatile SingularAttribute<Account,Integer> accountstatus;
    public static volatile SingularAttribute<Account,Integer> accounttype;
    public static volatile SingularAttribute<Account,String> aliasname;
    public static volatile SingularAttribute<Account,String> id;
    public static volatile SingularAttribute<Account,Long> logincount;
    public static volatile SingularAttribute<Account,String> name;
    public static volatile SingularAttribute<Account,String> passwd;
}
