/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.water.metamodel.account;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.water.metamodel.account.AccountOperatorLog.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Wed Jul 17 13:16:01 CST 2013")
public class AccountOperatorLog_ {
    public static volatile SingularAttribute<AccountOperatorLog,AccountLog> accountLog;
    public static volatile SingularAttribute<AccountOperatorLog,String> content;
    public static volatile SingularAttribute<AccountOperatorLog,String> id;
}
