/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.water.metamodel.account;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.water.metamodel.account.AccountWeb.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Wed Jul 17 13:16:01 CST 2013")
public class AccountWeb_ {
    public static volatile SingularAttribute<AccountWeb,String> accountid;
    public static volatile SingularAttribute<AccountWeb,String> email;
    public static volatile SingularAttribute<AccountWeb,String> mobile;
    public static volatile SingularAttribute<AccountWeb,String> telephone;
    public static volatile SingularAttribute<AccountWeb,String> truename;
}
