/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.water.metamodel.tree;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.water.metamodel.tree.Category.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Wed Jul 17 13:17:29 CST 2013")
public class Category_ {
    public static volatile SingularAttribute<Category,String> abbreviation;
    public static volatile SingularAttribute<Category,String> categorytype;
    public static volatile SingularAttribute<Category,String> code;
    public static volatile SingularAttribute<Category,String> id;
    public static volatile SingularAttribute<Category,String> imgsrc;
    public static volatile SingularAttribute<Category,String> name;
    public static volatile SingularAttribute<Category,String> parentid;
    public static volatile SingularAttribute<Category,String> status;
    public static volatile SingularAttribute<Category,String> url;
}
